// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe9OO_-alTYfIOL2PQN8LbCoyVfAqwB5g',
    appId: '1:239189465709:web:633174222b7e9913bbbd64',
    messagingSenderId: '239189465709',
    projectId: 'library-system-6ef13',
    authDomain: 'library-system-6ef13.firebaseapp.com',
    storageBucket: 'library-system-6ef13.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV7M3g1RxYyMXxd7wDaAp_F_YXHfPW14Q',
    appId: '1:239189465709:android:e022bb5c279a5f65bbbd64',
    messagingSenderId: '239189465709',
    projectId: 'library-system-6ef13',
    storageBucket: 'library-system-6ef13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDJhzHhZ82sDi8e_dFf0SHMwd2verWa1M',
    appId: '1:239189465709:ios:63cd480fc5fa44f4bbbd64',
    messagingSenderId: '239189465709',
    projectId: 'library-system-6ef13',
    storageBucket: 'library-system-6ef13.appspot.com',
    iosBundleId: 'com.example.libraryManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDJhzHhZ82sDi8e_dFf0SHMwd2verWa1M',
    appId: '1:239189465709:ios:528bd59481da2caebbbd64',
    messagingSenderId: '239189465709',
    projectId: 'library-system-6ef13',
    storageBucket: 'library-system-6ef13.appspot.com',
    iosBundleId: 'com.example.libraryManagement.RunnerTests',
  );
}
